name: Update Visitor Count

on:
  push:
    branches:
      - main

jobs:
  update-visitor-count:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run JavaScript
        run: |
          node index.js
        env:
          pat: ${{ secrets.pat }}
